add_executable(exo9 hello.c)
add_executable(exe10 convert_farh.c)
add_executable(exo11 convert_farh_update.c)
add_executable(exo12 convert_fahr_for.c)
add_executable(exo13 convert_fahr_define.c)
add_executable(exo14 copy_get_put.c)
add_executable(exo15 count.c)
add_executable(exo16 count2.c)
add_executable(exo17 count_lines.c)
add_executable(exo18 space.c)
add_executable(exo19 replacing.c)
add_executable(exo20 count_words.c)
add_executable(exo21 word_line.c)
add_executable(exo22 table.c)
add_executable(exo23 histogramme.c)
add_executable(exo24 histogramme_vertical.c)
add_executable(exo25 histogramme_freq.c)
add_executable(exo26 fonctions.c)
add_executable(exo27 fonction_conversion.c)
